services:
  app:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
    container_name: daryza_app
    restart: unless-stopped
    # ports:
    #   - "5173:5173"
    environment:
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: pgsql
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/var/www
      - './infrastructure/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini'
      # - './infrastructure/php/www.conf:/usr/local/etc/php-fpm.d/www.conf'

    depends_on:
      - postgresql
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: daryza_nginx
    restart: unless-stopped
    ports:
      - '8082:80'
    volumes:
      - .:/var/www
      - /var/www/node_modules # <- este es clave
      - ./infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - app
    networks:
      - laravel

  postgresql:
    image: postgres:15
    container_name: daryza_postgresql
    restart: unless-stopped
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - laravel
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}']
      interval: 5s
      retries: 5
      timeout: 5s

volumes:
  postgres:

networks:
  laravel:
    driver: bridge
